import { escapeHtml as e } from "./core/utils.js";
import { MEDIA_PRESETS, localExtrasState } from "./core/media-sites.js";
import { automaticAIStatus } from "./core/ai-policy.js";
import { guideText as c } from "./learning-view.js";
import { APP_VERSION } from "./core/release.js";

export function renderMediaPresets(origins = [], disabled = false) {
  return `<details class="media-presets mini-disclosure"><summary>${c("Common media sites", "Trang nghe nhìn phổ biến")}</summary>
    <p class="field-help">${c("Ready-to-select presets. Nothing is granted automatically. Player detection varies by site; playback never proves attention.", "Danh sách có sẵn để chọn. Không tự cấp quyền. Khả năng nhận diện tùy trình phát; phát nội dung không chứng minh sự chú ý.")}</p>
    <div class="preset-grid">${MEDIA_PRESETS.map(site => `<div class="media-preset"><div><strong>${e(site.name)}</strong><small>${e(site.origin)}</small></div><button type="button" class="btn compact ghost" data-action="${origins.includes(site.origin) ? "privacy-remove-site" : "privacy-add-preset"}" data-origin="${site.origin}" ${disabled ? "disabled" : ""}>${origins.includes(site.origin) ? c("Remove", "Gỡ") : c("Allow", "Cho phép")}</button></div>`).join("")}</div>
    <p class="field-help">${c("Reload the page after granting access. Recording also requires session tracking. Adding new presets in an update does not grant them access.", "Tải lại trang sau khi cấp quyền; cần bật ghi nhận phiên để thu thập. Trang bổ sung trong bản cập nhật không tự được cấp quyền.")}</p></details>`;
}

export function renderLocalExtrasToggle(activity, reminders, disabled = false) {
  const group = localExtrasState(activity, reminders);
  return `<section class="card local-bulk-card"><p class="eyebrow">${c("A shortcut, your choice", "Lựa chọn nhanh")}</p>
    <label class="check-row"><input type="checkbox" id="privacy-local-all" data-privacy="localAll" aria-describedby="local-all-help" ${group.all ? "checked" : ""} ${disabled ? "disabled" : ""}><span><strong>${c("Enable all local extras", "Bật các tính năng bổ sung trên máy")}</strong><small>${group.all ? c("All local extras enabled", "Đã bật tất cả tính năng trên máy") : group.some ? c(`Custom · ${group.count}/6 enabled`, `Tùy chỉnh · đã bật ${group.count}/6`) : c("Off · core tools still work", "Đang tắt · công cụ cơ bản vẫn dùng được")}</small></span></label>
    <p class="field-help" id="local-all-help">${c("Review a warning and the exact sites before enabling tracking, title/resource recording, media signals, background listening and reminders. AI, key storage and debug text have separate controls. Turning this off pauses these extras and keeps recorded history; Chrome grants are separate.", "Xem cảnh báo và từng trang trước khi bật theo dõi, lưu tiêu đề/tài nguyên, tín hiệu media, nghe nền và nhắc việc. AI, lưu khóa và nội dung gỡ lỗi có điều khiển riêng. Tắt sẽ dừng các tính năng này và giữ lịch sử; quyền Chrome là phần riêng.")}</p></section>`;
}

export function renderLocalExtrasDialog(origins, saving = false) {
  return `<div class="modal-backdrop"><section class="modal permission-review" role="dialog" aria-modal="true" aria-labelledby="local-review-title" aria-describedby="local-review-help">
    <p class="eyebrow">${c("Before you allow", "Trước khi cho phép")}</p><h2 id="local-review-title" tabindex="-1">${c("Enable local collection and reminders?", "Bật thu thập trên máy và nhắc việc?")}</h2>
    <p id="local-review-help">${c("This records website names, times, page titles and cleaned resource IDs on this device for 7 days. Titles can contain personal information. It also enables estimated background listening and desktop reminders, which may show task titles.", "Lưu tên trang, thời gian, tiêu đề và mã tài nguyên đã làm gọn trên máy trong 7 ngày. Tiêu đề có thể chứa thông tin cá nhân. Đồng thời bật ước tính nghe nền và thông báo có thể hiện tên công việc.")}</p>
    <p>${c("Selected sites can provide player-state signals. No audio, video, page text or keystrokes are captured. AI choices stay unchanged.", "Trang được chọn có thể cung cấp trạng thái trình phát. Không ghi âm, video, nội dung trang hay phím gõ. Lựa chọn AI không thay đổi.")}</p>
    <fieldset class="bulk-sites"><legend>${c("Sites included in this approval", "Các trang trong lần chấp thuận này")}</legend>${MEDIA_PRESETS.map(site => `<label class="check-row"><input type="checkbox" data-bulk-site="${site.origin}" ${origins.includes(site.origin) ? "checked" : ""} ${saving ? "disabled" : ""}><span>${e(site.name)}<small>${site.origin}</small></span></label>`).join("")}</fieldset>
    <p class="field-help">${c("Chrome will request tabs, idle and notifications, plus scripting and only the sites selected above. Existing approved sites are kept. Later presets are never added to this approval.", "Chrome sẽ xin quyền tabs, idle và notifications, thêm scripting cùng đúng các trang đã chọn. Giữ các trang đã cho phép trước đó. Trang thêm về sau không thuộc lần chấp thuận này.")}</p>
    <div class="button-row"><button class="btn primary" type="button" data-action="confirm-local-extras" ${saving ? "disabled" : ""}>${c("Enable these choices", "Bật các lựa chọn này")}</button><button class="btn ghost" type="button" data-action="close-modal" ${saving ? "disabled" : ""}>${c("Keep my current choices", "Giữ lựa chọn hiện tại")}</button></div></section></div>`;
}

export function renderAIPolicy(policy, connected, saving = false) {
  if (!policy) return `<p class="privacy-note" role="status">${c("AI controls could not be read. Reopen this screen to retry; local tools remain available.", "Chưa đọc được điều khiển AI. Mở lại màn hình để thử; công cụ trên máy vẫn dùng được.")}</p>`;
  const status = automaticAIStatus(policy), disabled = saving ? "disabled" : "";
  return `<section class="card ai-policy-card"><div class="card-header"><h2>${c("AI on your terms", "AI theo lựa chọn riêng")}</h2><span class="status-chip">${!connected ? c("Not connected", "Chưa kết nối") : status === "manual" ? c("Only when I ask", "Chỉ khi yêu cầu") : status === "budget" ? c("Paused for today", "Tạm dừng hôm nay") : c("Automatic AI allowed", "Cho phép AI tự động")}</span></div>
    <p class="field-help">${c("Connecting AI does not enable browser collection. Choose each automatic feature separately; a connected key alone does not start it.", "Kết nối AI không bật thu thập trình duyệt. Chọn riêng từng tính năng tự động; chỉ kết nối khóa không tự chạy chúng.")}</p>
    <label class="field" for="ai-mode">${c("When AI can run", "Khi nào AI được chạy")}<select class="select" id="ai-mode" ${disabled} ${!connected ? "disabled" : ""}><option value="manual" ${!policy.automaticEnabled ? "selected" : ""}>${c("Only when I ask", "Chỉ khi yêu cầu")}</option><option value="automatic" ${policy.automaticEnabled ? "selected" : ""}>${c("Also allow selected automatic features", "Cho phép thêm tính năng tự động đã chọn")}</option></select></label>
    <form id="ai-budget-form"><label class="field" for="ai-daily-limit">${c("Shared automatic requests per day", "Giới hạn yêu cầu tự động mỗi ngày")}<input id="ai-daily-limit" name="dailyLimit" class="input" type="number" min="0" max="100" step="1" required value="${policy.dailyLimit}" ${disabled}></label><button class="btn compact" type="submit" ${disabled}>${c("Save limit", "Lưu giới hạn")}</button></form>
    <p class="field-help">${c(`${policy.used}/${policy.dailyLimit} automatic attempts today · sorting ${policy.byFeature.sorting}, activity ${policy.byFeature.activity}, memory ${policy.byFeature.memory}.`, `${policy.used}/${policy.dailyLimit} lượt tự động hôm nay · phân loại ${policy.byFeature.sorting}, hoạt động ${policy.byFeature.activity}, ghi nhớ ${policy.byFeature.memory}.`)}</p>
    <p class="field-help">${c("Failed requests count. Resets with the device's local day. This is your app limit, not Google's remaining quota. Manual requests are separate; existing per-feature limits still apply. A zero limit pauses automatic requests.", "Yêu cầu thất bại vẫn tính. Đặt lại theo ngày địa phương của thiết bị. Đây là giới hạn trong ứng dụng, không phải hạn mức Google còn lại. Yêu cầu thủ công tính riêng; giới hạn từng tính năng vẫn áp dụng. Đặt 0 để dừng yêu cầu tự động.")}</p></section>`;
}

export function renderAIWarning() {
  return `<div class="modal-backdrop"><section class="modal permission-review" role="dialog" aria-modal="true" aria-labelledby="ai-review-title"><h2 id="ai-review-title" tabindex="-1">${c("Allow selected AI features to run automatically?", "Cho phép các tính năng AI đã chọn tự chạy?")}</h2><p>${c("Separately enabled sorting, activity attribution and memory learning may send their disclosed task, title or memory context to Google without another click. They share your daily automatic-request limit; provider charges and limits still apply.", "Phân loại, gán nhãn hoạt động và học ghi nhớ đã bật riêng có thể gửi ngữ cảnh công việc, tiêu đề hoặc ghi nhớ đã công bố đến Google mà không cần bấm thêm. Dùng chung giới hạn tự động mỗi ngày; phí và hạn mức nhà cung cấp vẫn áp dụng.")}</p><p>${c("This does not enable those features, browser collection, instruction sharing, saved-memory sharing or debug text. Turn this mode off to stop future automatic requests. Data already sent cannot be recalled here.", "Thao tác này không bật các tính năng đó, thu thập trình duyệt, chia sẻ hướng dẫn/ghi nhớ hay nội dung gỡ lỗi. Tắt chế độ để dừng yêu cầu tự động về sau. Không thể thu hồi dữ liệu đã gửi tại đây.")}</p><div class="button-row"><button class="btn primary" type="button" data-action="confirm-automatic-ai">${c("Allow selected automation", "Cho phép tự động đã chọn")}</button><button class="btn ghost" type="button" data-action="close-modal">${c("Keep manual only", "Giữ chế độ thủ công")}</button></div></section></div>`;
}

export function renderAbout() {
  return `<div class="header-copy"><p class="eyebrow">Stuđiô · ${APP_VERSION}</p><h1 class="page-title">${c("Make room for what matters.", "Dành chỗ cho điều quan trọng.")}</h1></div><div class="stack"><section class="card about-card"><h2>${c("Time management with less management", "Quản lý thời gian, bớt thao tác")}</h2><p>${c("A task, a little time, one next step. Core planning and focus tools run locally; tracking and AI are choices you control.", "Một việc, một khoảng thời gian, một bước tiếp theo. Công cụ lập kế hoạch và tập trung chạy trên máy; theo dõi và AI do mỗi người lựa chọn.")}</p></section><section class="card"><p class="eyebrow">${c("Design inspiration", "Cảm hứng thiết kế")}</p><h2>MD Studio</h2><p>${c("The calm hierarchy, expressive time displays and thoughtful everyday details of MD Studio's apps inspired this visual direction. Stuđiô's interface, illustrations and implementation are original. This is an independent project, with no affiliation or endorsement.", "Bố cục rõ ràng, cách thể hiện thời gian và chi tiết hằng ngày trong ứng dụng MD Studio truyền cảm hứng cho hướng thiết kế này. Giao diện, minh họa và mã nguồn Stuđiô được tạo riêng. Dự án độc lập, không liên kết hay được MD Studio bảo trợ.")}</p><div class="about-links"><a href="https://apps.apple.com/us/developer/md-studio/id1438854445" target="_blank" rel="noopener noreferrer">MD Studio ↗</a><a href="https://apps.apple.com/app/id1474340105" target="_blank" rel="noopener noreferrer">OffScreen ↗</a><a href="https://apps.apple.com/us/app/md-clock-flip-clock/id1536358464" target="_blank" rel="noopener noreferrer">MD Clock ↗</a><a href="https://apps.apple.com/us/app/md-vinyl-music-app/id1606306441" target="_blank" rel="noopener noreferrer">MD Vinyl ↗</a></div></section><section class="card"><h2>${c("Your data, your choices", "Dữ liệu và lựa chọn riêng")}</h2><p>${c("Browser activity is an estimate, not proof of attention or task completion. Open Privacy choices to inspect collection and sharing. Explain this screen and Help & tours are always available when you need them.", "Hoạt động trình duyệt là ước tính, không chứng minh sự chú ý hay hoàn thành việc. Mở Lựa chọn riêng tư để kiểm tra thu thập/chia sẻ. Có thể dùng Giải thích màn hình và Trợ giúp & hướng dẫn khi cần.")}</p><button class="btn" type="button" data-action="open-privacy">${c("Privacy choices", "Lựa chọn riêng tư")}</button></section></div>`;
}
