import { t, html, msg, markup, setLanguage, getLocale } from "./i18n.js";
import { MEMORY_SCOPES, memoryOverview, pendingEvidence } from "./core/learned-memory.js";
import { escapeHtml, localDateTimeInput } from "./core/utils.js";

const labels = { explicit: "Explicit", confirmed: "Confirmed", observation: "Supported observation", tentative: "Tentative inference", conflict: "Conflict · review needed" };
const dateLabel = value => value ? new Date(value).toLocaleString(getLocale()) : t("Not yet");
const option = (value, selected) => html`<option value="${value}" ${value === selected ? "selected" : ""}>${value === "device-use" ? t("Digital-device use") : t(value[0].toUpperCase() + value.slice(1))}</option>`;

export function renderLearnedSettings(store, { busy = false, installed = true, connected = false, dayEnd = "21:30", noteText = "", noteScope = "general" } = {}) {
  if (!store) return html`<section class="card"><h2>Saved memory</h2><p>The memory store could not be read.</p><button class="btn" type="button" data-action="learned-refresh-view">Retry</button></section>`;
  const overview = memoryOverview(store);
  const disabled = busy || !installed ? "disabled" : "";
  const records = store.memories.slice().reverse();
  const recentContext = store.lastContext?.memoryIds.map(id => store.memories.find(item => item.id === id)).filter(Boolean) ?? [];
  return html`<section class="card" aria-labelledby="learned-title">
    <div class="card-header"><div><p class="eyebrow">Memory from use</p><h2 id="learned-title">Saved memory</h2></div><span class="status-chip">${overview.active} active</span></div>
    <p class="subtle">Keep useful preferences and observations with their sources. Your Custom Instructions stay under your control.</p>
    <label class="check-row"><input id="learned-use" type="checkbox" ${store.settings.useWithGemini ? "checked" : ""} ${disabled}><span><strong>Use saved memory in assistance</strong><br>Include relevant explicit memories and supported observations in assistance requests. Tentative entries wait for confirmation. Learning updates have their own separate switch below.</span></label>
    <label class="check-row"><input id="learned-learning" type="checkbox" ${store.settings.learningEnabled ? "checked" : ""} ${disabled}><span><strong>Learn from my activity</strong><br>Off by default. When enabled, new task titles, task edits, timer records, and learning notes can be sent to Gemini in background updates, together with existing saved memories and enabled Custom Instructions. Previous feedback and debug history are excluded. Pausing deletes pending learning evidence and keeps saved memories and their supporting history.</span></label>
    <p class="field-help">One automatic batch per active day near ${escapeHtml(dayEnd)}, or after reopening if missed. At most 3 memory requests per local day, including manual refreshes and failed attempts. No new evidence means no API call. Your selected Gemini model is used.</p>
    <div class="memory-meta"><span>${overview.pending} pending events · ${overview.tentative} entries to review</span><span>Update: ${escapeHtml(t(store.status.replaceAll("_", " ")))}</span></div>
    <p class="field-help">Last successful update: ${escapeHtml(dateLabel(store.lastSuccessAt))}${store.retryAfter && new Date(store.retryAfter) > new Date() ? msg` · Retry after ${escapeHtml(dateLabel(store.retryAfter))}` : ""}</p>
    ${store.lastError ? html`<p class="memory-notice" role="status">${escapeHtml(t(store.lastError))}</p>` : ""}
    <div class="button-row"><button class="btn primary" type="button" data-action="learned-add" ${disabled}>Add a memory</button><button class="btn" type="button" data-action="learned-update" ${disabled || !connected || !store.settings.learningEnabled || store.job ? "disabled" : ""}>${store.job ? t("Updating…") : t("Refresh memory now")}</button><button class="btn danger ghost" type="button" data-action="learned-ask-clear" ${disabled}>Clear learned data</button></div>
    ${!installed ? markup('<p class="field-help">Memory controls are available in the installed extension.</p>') : !connected ? markup('<p class="field-help">You can manage explicit memories locally. Connect Gemini to process learning evidence.</p>') : ""}
    <div class="memory-list">${records.length ? records.map(record => {
      const expired = record.expiresAt && new Date(record.expiresAt) <= new Date();
      const evidence = record.evidenceIds.map(id => store.evidence.find(item => item.id === id)).filter(Boolean);
      return html`<article class="memory-entry"><div class="memory-meta"><span>${escapeHtml(t(labels[record.status]))} · ${escapeHtml(t(record.scope[0].toUpperCase() + record.scope.slice(1)))}</span>${expired ? markup('<span>Expired · excluded from requests</span>') : record.expiresAt ? html`<span>Until ${escapeHtml(dateLabel(record.expiresAt))}</span>` : ""}</div><p class="memory-text">${escapeHtml(record.text)}</p><details class="mini-disclosure"><summary>Why this is saved</summary><p>Source: ${escapeHtml(t(record.source))}. Last supported: ${escapeHtml(dateLabel(record.lastSupportedAt))}.</p>${evidence.length ? evidence.map(item => html`<p>${escapeHtml(dateLabel(item.at))} · ${escapeHtml(t(item.origin))}<br>${escapeHtml(item.title)} ${escapeHtml(item.detail)}${item.beforeMinutes !== null ? html`<br>Minutes: ${item.beforeMinutes} → ${item.afterMinutes}` : ""}</p>`).join("") : markup('<p>Explicitly saved or confirmed, or the original evidence has aged out.</p>')}</details><div class="button-row"><button class="btn compact" type="button" data-action="learned-edit" data-memory-id="${escapeHtml(record.id)}" ${disabled}>Edit</button>${["tentative", "conflict", "observation"].includes(record.status) ? html`<button class="btn compact" type="button" data-action="learned-confirm" data-memory-id="${escapeHtml(record.id)}" ${disabled}>Confirm</button>` : ""}<button class="btn compact danger ghost" type="button" data-action="learned-ask-forget" data-memory-id="${escapeHtml(record.id)}" ${disabled}>Forget</button></div></article>`;
    }).join("") : markup('<p class="empty-copy">No saved memories yet. Add one directly or enable learning and use Stuđiô.</p>')}</div>
    <details class="mini-disclosure"><summary>What informed the last Gemini request?</summary>${store.lastContext ? html`<p>${escapeHtml(t(store.lastContext.action))} · ${escapeHtml(dateLabel(store.lastContext.at))}</p>${recentContext.map(record => html`<p>${escapeHtml(record.text)}</p>`).join("") || markup("<p>The referenced entries are no longer available.</p>")}` : markup("<p>No current memory-context record is available. Custom Instructions have their own control above.</p>")}</details>
    <details class="mini-disclosure"><summary>Recent memory changes</summary>${store.history.length ? store.history.slice(-8).reverse().map(change => {
      const canUndo = !change.undone && change.after && store.memories.find(item => item.id === change.memoryId)?.revision === change.after.revision;
      return html`<article class="memory-entry"><p>${escapeHtml(t(change.action))} · ${escapeHtml(dateLabel(change.at))}</p>${change.before ? html`<p class="field-help">Before: ${escapeHtml(change.before.text)}</p>` : ""}${change.after ? html`<p>${escapeHtml(change.after.text)}</p>` : ""}${canUndo ? html`<button class="btn compact" type="button" data-action="learned-undo" data-change-id="${escapeHtml(change.id)}" ${disabled}>Undo this change</button>` : change.undone ? markup('<p class="field-help">Undone</p>') : ""}</article>`;
    }).join("") : markup("<p>No changes recorded.</p>")}</details>
    <details class="mini-disclosure"><summary>Pending learning evidence</summary>${pendingEvidence(store).slice(0, 40).map(item => html`<p>${escapeHtml(dateLabel(item.at))} · ${escapeHtml(item.type)}<br>${escapeHtml(item.title)} ${escapeHtml(item.detail)}</p>`).join("") || markup("<p>Nothing pending.</p>")}</details>
    <details class="mini-disclosure"><summary>Add an observation for learning</summary><p>This new note will be included in the next Gemini memory update. Use Add a memory to save a direct instruction locally.</p><form id="learning-note-form"><div class="field"><label for="learning-note">What should Stuđiô consider?</label><textarea id="learning-note" name="text" class="textarea" maxlength="1600" ${disabled || !store.settings.learningEnabled ? "disabled" : ""}>${escapeHtml(noteText)}</textarea></div><div class="field"><label for="learning-note-scope">Topic</label><select id="learning-note-scope" name="scope" class="input" ${disabled}>${MEMORY_SCOPES.map(scope => option(scope, noteScope)).join("")}</select></div><button class="btn" type="submit" ${disabled || !store.settings.learningEnabled ? "disabled" : ""}>Queue observation</button></form></details>
    <p class="field-help">Timer records describe elapsed timer time, not attention. Browser tracking is separate from memory learning. Memory updates cannot start timers or change tasks and schedules.</p>
  </section>`;
}

export function renderLearnedEditor(draft, busy = false) {
  return html`<div class="modal-backdrop"><section class="modal" role="dialog" aria-modal="true" aria-labelledby="learned-editor-title"><div class="modal-head"><div><h2 id="learned-editor-title">${draft.id ? t("Edit memory") : t("Add a memory")}</h2><p>Saved locally as explicit guidance. No API call is made.</p></div><button class="btn ghost" type="button" data-action="close-modal" ${busy ? "disabled" : ""}>Close</button></div><form id="learned-memory-form"><div class="field"><label for="learned-text">Memory</label><textarea id="learned-text" name="text" class="textarea" rows="5" maxlength="600" required autofocus ${busy ? "disabled" : ""}>${escapeHtml(draft.text ?? "")}</textarea></div><div class="field-grid"><div class="field"><label for="learned-scope">Topic</label><select id="learned-scope" class="input" name="scope">${MEMORY_SCOPES.map(scope => option(scope, draft.scope ?? "general")).join("")}</select></div><div class="field"><label for="learned-kind">Kind</label><select id="learned-kind" class="input" name="kind">${["context", "preference", "observation"].map(kind => option(kind, draft.kind ?? "context")).join("")}</select></div></div><div class="field"><label for="learned-expiry">Expires (optional, local time)</label><input id="learned-expiry" name="expiresAt" class="input" type="datetime-local" value="${escapeHtml(draft.expiryInput ?? (draft.expiresAt ? localDateTimeInput(draft.expiresAt) : ""))}"></div><button class="btn primary" type="submit" ${busy ? "disabled" : ""}>Save memory</button></form></section></div>`;
}
