import { t, html, msg, markup, setLanguage, getLocale } from "./i18n.js";
import { escapeHtml } from "./core/utils.js";

export function renderPlanningAssistant({ mode = "guided", connected = false, working = false, saving = false, advice = null, guidance = null, reflection = "", draft = {}, tasks = [], manualOnly = false } = {}) {
  const guided = mode !== "suggest";
  const controls = html`<div class="field"><label for="planning-mode">Planning assistance</label><select id="planning-mode" class="input" ${working || saving ? "disabled" : ""}><option value="guided" ${guided ? "selected" : ""}>Guide me · I make the plan</option><option value="suggest" ${!guided ? "selected" : ""}>Suggest my next step</option></select></div>`;
  const disclosure = markup('<p class="field-help">When you ask Gemini: up to 20 active tasks and short notes, upcoming blocks, recorded timer totals, enabled Custom Instructions, and relevant saved memories are sent. Nothing is saved or started automatically.</p>');
  if (!guided && !manualOnly) return html`<section class="card"><p class="eyebrow">Optional planning help</p><h2>Suggest my next step</h2>${controls}<p class="subtle">Ask for a few options based on your current tasks. You decide whether to use any of them.</p><button class="btn soft" type="button" data-action="day-advice" ${!connected || working ? "disabled" : ""}>${working ? t("Thinking…") : t("Ask for suggestions")}</button>${!connected ? markup('<p class="field-help">Connect Gemini to request suggestions, or choose Guide me to plan locally.</p>') : ""}${advice ? html`<div class="explanation"><p>${escapeHtml(advice.overview)}</p>${advice.suggestions.map((item, index) => html`<article class="memory-entry"><h3>${escapeHtml(item.title)}</h3><p>${escapeHtml(item.reason)}</p><p class="field-help">${item.durationMinutes} minutes suggested as a starting interval</p><button class="btn compact" type="button" data-action="advice-use" data-suggestion-index="${index}">${item.taskId ? t("Review focus setup") : t("Write a task manually")}</button></article>`).join("")}</div>` : ""}${disclosure}</section>`;
  const output = draft.output === "block" ? "block" : "task";
  const existing = output === "block" && Boolean(draft.taskId);
  const list = (title, items) => items?.length ? html`<h3>${title}</h3><ul>${items.map(item => html`<li>${escapeHtml(item)}</li>`).join("")}</ul>` : "";
  return html`<section class="card">${manualOnly ? "" : html`<h2>Guide me</h2>${controls}<p class="subtle">Use the questions below, then write and schedule your own work. The form stays yours—even after Gemini offers ideas.</p>
    <ol><li>What outcome matters to you now?</li><li>What is one concrete action, and how much time do you want to give it?</li><li>Does it fit your existing commitments? Choose a start time if you want a block.</li></ol>
    <details class="mini-disclosure"><summary>Optional Gemini brainstorming</summary><form id="guide-help-form"><div class="field"><label for="guide-reflection">What are you considering or stuck on?</label><textarea id="guide-reflection" name="reflection" class="textarea" maxlength="1200" required ${working ? "disabled" : ""}>${escapeHtml(reflection)}</textarea></div><button class="btn soft" type="submit" ${!connected || working ? "disabled" : ""}>${working ? t("Thinking…") : t("Help me think it through")}</button></form>${!connected ? markup('<p class="field-help">Gemini is not connected. The questions and manual form still work.</p>') : ""}${disclosure}</details>
    ${guidance ? html`<div class="explanation"><p>${escapeHtml(guidance.overview)}</p>${list(t("Questions to consider"), guidance.questions)}${list(t("Planning steps"), guidance.steps)}${list(t("Ideas—not assignments"), guidance.ideas)}</div>` : ""}
    `}<details class="mini-disclosure" ${draft.editing ? "open" : ""}><summary>Write my task or focus block</summary><form id="guided-plan-form">
      <div class="field"><label for="guide-output">I want to create</label><select id="guide-output" name="output" class="input" data-guide-field="output" ${saving ? "disabled" : ""}><option value="task" ${output === "task" ? "selected" : ""}>A task, without a scheduled time</option><option value="block" ${output === "block" ? "selected" : ""}>A focus block at my chosen time</option></select></div>
      ${output === "block" ? html`<div class="field"><label for="guide-task">Task for this block</label><select id="guide-task" name="taskId" class="input" data-guide-field="taskId" ${saving ? "disabled" : ""}><option value="">A new task I write below</option>${tasks.map(task => html`<option value="${escapeHtml(task.id)}" ${draft.taskId === task.id ? "selected" : ""}>${escapeHtml(task.title)}</option>`).join("")}</select></div>` : ""}
      ${!existing ? html`<div class="field"><label for="guide-title">My concrete action</label><input id="guide-title" name="title" class="input" data-guide-field="title" maxlength="160" value="${escapeHtml(draft.title ?? "")}" placeholder="Write this yourself" required ${saving ? "disabled" : ""}></div><div class="field"><label for="guide-notes">My notes (optional)</label><textarea id="guide-notes" name="notes" class="textarea" data-guide-field="notes" maxlength="4000" ${saving ? "disabled" : ""}>${escapeHtml(draft.notes ?? "")}</textarea></div>` : ""}
      <div class="field-grid"><div class="field"><label for="guide-duration">My estimate (minutes)</label><input id="guide-duration" name="durationMinutes" type="number" min="5" max="180" step="1" class="input" data-guide-field="durationMinutes" value="${escapeHtml(draft.durationMinutes ?? "")}" required ${saving ? "disabled" : ""}></div>${output === "block" ? html`<div class="field"><label for="guide-start">My start time (local)</label><input id="guide-start" name="startAt" type="datetime-local" class="input" data-guide-field="startAt" value="${escapeHtml(draft.startAt ?? "")}" required ${saving ? "disabled" : ""}></div>` : ""}</div>
      <button class="btn primary" type="submit" ${saving ? "disabled" : ""}>${saving ? t("Saving…") : output === "block" ? t("Save my focus block") : t("Save my task")}</button><p class="field-help">Only your form values are saved. A block is checked for overlaps; its timer will not start until you choose to start it.</p>
    </form></details>
  </section>`;
}
